### ISSUE TITLE
After downloading update how can I delete the previous installed version on the phone to save storage?

### ISSUE THREAD

**Issue by deliverymanager** [driftyco/ionic-plugin-deploy#100]
After update I can see the app data in the phone increase by 22MB.
This is almost the size of my app and I believe this happens due to the fact that the apps internally holds the zip of the app.
If I make another update then the data increases even more!
So every time I make an app update, the data that the phone holds increases by 22MB.
So the question is how can the app delete any previously installed versions of the app downloaded from ionic cloud services?

**Comment by deliverymanager** [comment]
I have found the answer to the Ionic Cloud Docs.
$ionicDeploy.getSnapshots().then(function(snapshots) {
  // snapshots will be an array of snapshot uuids
});
$ionicDeploy.deleteSnapshot('366f119a-4d3b-46fd-b1be-1def98812344');

**Comment by nikmartin** [comment]
In case anyone else is looking to do this, you have no make sure you don't  delete your current snapshot: 

```

this.deploy.getSnapshots().then(snapshots => {
          console.log('Snapshots: ' + snapshots);
          this.deploy.info().then(x => {
            console.log('Current snapshot info: ' + x);
            for (let suuid of snapshots) {
              if (suuid !== x.deploy_uuid) {
                this.deploy.deleteSnapshot(suuid);
              }
            }
          });
        });
```
