### ISSUE TITLE
Using @Inject

### ISSUE THREAD

**Issue by kodeine** [driftyco/ionic-plugin-deploy#104]
Hello,
I'm trying to inject it dynamically. i've put 

`{ provide: 'Deploy', useClass: Deploy, deps: [CloudConfig, EventEmitter, Logger] },`

in providers but it doesnt work. can you please help how can i properly inject?

Thanks

**Comment by ericb** [comment]
Is there a reason you're not using the standard cloud client [setup](http://docs.ionic.io/setup.html)? I'm not even sure we can support this, but @dwieeb may be able to add more context.

**Comment by dwieeb** [comment]
Using the `CloudModule.forRoot(cloudSettings)` is the key here. That single line defines how to inject our classes.

**Comment by kodeine** [comment]
i was trying to move the updater code to a different class and call the object in app.component.ts, when i move to another class i need to inject Deploy in constructor?

**Comment by dwieeb** [comment]
Yes, that's what you'll need to do in Angular for all injected services. See the [dependency injection docs](https://angular.io/docs/ts/latest/guide/dependency-injection.html).
