### ISSUE TITLE
App store version compare ionic deploy version

### ISSUE THREAD

**Issue by gladiacxtylish** [driftyco/ionic-plugin-deploy#105]
This is the flow I have currently.

1. Installed 1.0.0 from app store
2. Pushed 1.1.0 to ionic deploy
3. App detected there is an update from ionic deploy, installed it
4. Published 1.2.0 to app store without pushing to ionic deploy
5. App detected there is an update from ionic deploy, installed it (problem)

My question is that isn't ionic deploy supposed to know 1.2.0 is newer and skip the version from ionic deploy?

I also tried to push 1.2.0 to ionic deploy together with publishing to app store in the step 4. The app would still think there is an update. It seems that ionic deploy will think there is an update as long as the snapshot on ionic deploy was never installed on the phone regardless on the version. Am I doing something wrong? How should I be using it?

**Comment by itrethan** [comment]
The current version comparison is confusing, do we have a deterministic way to figure out the which version is the newer?

**Comment by ericb** [comment]
Is this using the latest version of the plugin?

**Comment by jay8585** [comment]
I had same problem before.
But I fixed it by putting Equivalent Version on deploy info.
![image](https://cloud.githubusercontent.com/assets/8064923/20584764/3318a77a-b239-11e6-8446-114b5670bc05.png)
