### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by dhyegofernando** [driftyco/ionic-plugin-deploy#106]
I made everything like you said in docs but after load() it shows me the following error:
```
Failed to load webpage with error: The operation couldn’t be completed. (NSURLErrorDomain error -999.)
```

And the app just get crushed. What it could be?

**Comment by piotrowski** [comment]
What docs are you referring to?
What library are you using and how exactly did you implement it?
Does anything else of Ionic Deploy work?

> NSURLErrorDomain error -999

means that some task was "cancelled":

> NSURLSession sends this error to its delegate when a task is cancelled.

https://developer.apple.com/reference/foundation/1508628-url_loading_system_error_codes/nsurlerrorcancelled?language=objc

**Comment by dhyegofernando** [comment]
@piotrowski but it's a long time ago... and I can't remember what this error was, but thank you anyway for your time! 👍 👍
