### ISSUE TITLE
Feature request: get uuid of pending deploy

### ISSUE THREAD

**Issue by AgDude** [driftyco/ionic-plugin-deploy#109]
I can use the "info" method to get the current deployment, but I would like to get information about the snapshot I just downloaded before I extra/load it. while this may or may not be useful within the app, I would like to send it to a remote logging service, so I have something like this:

```
$ionicDeploy.download();
        .then(function () {
          return $ionicDeploy.extract();
        })
       .then(function () {
            return $ionicDeploy.info();
        })
        .then(function (info) {
          remoteLog.info(`Updating device from ${info.deploy_uuid} to ${new_uuid}`);
          return $ionicDeploy.load();
        })
```

**Comment by ericb** [comment]
While maybe not the best interface as-is, this can be done using a combination of the `check` and `getMetadata` methods shown [here](http://docs.ionic.io/services/deploy/#metadata).
