### ISSUE TITLE
Whitescreen during the deploy.load()

### ISSUE THREAD

**Issue by Clemouuche** [driftyco/ionic-plugin-deploy#112]
Hello,

all the deploy functions work fine but it's a bit confusing to have a whitescreen during the app relaunching. Is there a way to avoid that ?

Here is my code 

`this.deploy.check().then((snapAvailable: boolean) => {
     if (snapAvailable && (Network.connection !== 'cellular' || Network.connection !== '2g')) {
       this.deploy.download().then(() => {
         this.deploy.extract().then(() => {
           this.deploy.load()
         })
       })
     }
   })`

**Comment by MissCuriosity** [comment]
May i ask whether you have solved this problem?

**Comment by kodeine** [comment]
same here

**Comment by ericb** [comment]
I believe this is just due to the webview hard refreshing. You could attempt to show the splash screen before you call load or alternatively notify the user that updates will be applied when they next open the app.
