### ISSUE TITLE
How do I find out the valid serverUrl for my ionic app?

### ISSUE THREAD

**Issue by jacksonkr** [driftyco/ionic-plugin-deploy#119]
I have an app uploaded to ionic but I have no way to download it without a valid serverUrl. I keep getting "download error".

How do I find out the valid serverUrl for my app?

**Comment by piotrowski** [comment]
Where would you put this `serverUrl`?

Normally this Cordova plugin here is used via a library for Ionic:
https://github.com/driftyco/ionic-cloud for Ionic v1
https://github.com/driftyco/ionic-cloud-angular for all newer Ionic versions (2+)

**Comment by piotrowski** [comment]
But I actually found out the value of `serverUrl` here: https://github.com/driftyco/ionic-plugin-deploy/issues/115#issuecomment-302120230
