### ISSUE TITLE
Deploy fails during extraction

### ISSUE THREAD

**Issue by tumbl3w33d** [driftyco/ionic-plugin-deploy#122]
**Versions**
```
npm (global):
    @ionic/cli-utils : 1.0.0-beta0
    cordova          : 6.5.0 
    ionic            : 3.0.0-beta9

npm (local):
    @ionic/app-scripts              : 1.3.5
    @ionic/cli-plugin-cordova       : 1.0.0-beta0
    @ionic/cli-plugin-ionic-angular : 1.0.0-beta0
    Ionic Framework                 : ionic-angular 3.1.0

System:
    Node       : v7.9.0
    OS         : Linux 4.9
```

[package.json](https://gist.github.com/tumbl3w33d/34f405470bb4f734e805bf3c495f0933)

**Steps to reproduce:**
1. `ionic cordova build android`
2. `ionic upload`
3. deploy the uploaded snapshot to the dev channel
4. execute typical check -> download -> extract -> reload procedure in app  
```
this.deploy.download().then(() => {
      this.deploy.extract().then(() => {
        this.deploy.load()
      })
    })
```

**Expected results:**
Latest snapshot is loaded and running in the app now.

**Actual results:**
* the snapshot extraction fails
* according to `deploy.info()` the app is running the new snapshot
* changes didn't get deployed
```
04-27 21:13:31.830 11571 12326 I IONIC.DEPLOY.DOWNLOAD: Progress: 100%
04-27 21:13:31.835 11571 11571 D SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 65539 : Ionic Deploy: download complete
04-27 21:13:31.835 11571 11571 I chromium: [INFO:CONSOLE(65539)] "Ionic Deploy: download complete", source: file:///android_asset/www/build/main.js (65539)
04-27 21:13:31.840 11571 11571 D SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 47598 : snapshot downloaded
04-27 21:13:31.840 11571 11571 I chromium: [INFO:CONSOLE(47598)] "snapshot downloaded", source: file:///android_asset/www/build/main.js (47598)
04-27 21:13:31.840 11571 11638 I IONIC.DEPLOY.EXTRACT: Extracting update
04-27 21:13:31.840 11571 12325 I IONIC.DEPLOY.UNZIP: 0814e662-8a02-44d8-87c0-1c5e7c1d480f
04-27 21:13:31.840 11571 12325 I IONIC.DEPLOY.HASVER: Checking 0814e662-8a02-44d8-87c0-1c5e7c1d480f...
04-27 21:13:31.840 11571 12325 I IONIC.DEPLOY.HASVER: No
04-27 21:13:31.840 11571 12325 I IONIC.DEPLOY.UNZIP_DIR: /data/user/0/de.example.app/app_0814e662-8a02-44d8-87c0-1c5e7c1d480f
04-27 21:13:31.845 11571 12325 I IONIC.DEPLOY.ENTRIES: Total: 40
04-27 21:13:31.845 11571 12325 I IONIC.DEPLOY.EXTRACT: Progress: 2%
04-27 21:13:31.845 11571 12325 I IONIC.DEPLOY.EXTRACT: Progress: 5%
04-27 21:13:31.850 11571 12325 I IONIC.DEPLOY.EXTRACT: Progress: 7%
04-27 21:13:31.855 11571 12325 I IONIC.DEPLOY.EXTRACT: Progress: 10%
04-27 21:13:31.860 11571 12325 I IONIC.DEPLOY.EXTRACT: Progress: 12%
04-27 21:13:31.860 11571 12325 I IONIC.DEPLOY.UNZIP_STEP: Exception: /data/user/0/de.example.app/app_0814e662-8a02-44d8-87c0-1c5e7c1d480f/./assets/fonts: open failed: ENOTDIR (Not a directory)
04-27 21:13:31.920 11571 12325 I IONIC.DEPLOY.REMOVE: Removed www.zip
04-27 21:13:31.940 11571 11571 D SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 1507 : ERROR
04-27 21:13:31.940 11571 11571 I chromium: [INFO:CONSOLE(1507)] "ERROR", source: file:///android_asset/www/build/main.js (1507)
```
**Side notes:**
* there was a similar issue 2y ago: #12 
* on several attempts the error message shows different files as the culprit, so it's not like there's something wrong with the main.js

**Comment by panoti** [comment]
I catched "/assets/fonts: open failed: ENOTDIR (Not a directory)" the same. I created "fonts" folder but not solved this problems.

**Comment by demirk4n** [comment]
Same issue for "/assets/icon" folder.

**Comment by Fuiste** [comment]
Hey all,

Looks like this issue is tied to version 3.x.x of the CLI.  We're looking into the change to upload that caused it, but in the meantime you can get around the bug with 2.x.x version.

Sorry for the trouble there.

**Comment by Fuiste** [comment]
Looks like I was incorrect in that first update.  I've found the bug in our handling of the zip file for the android platform and pushed an update.  

Check out v0.6.7, which addresses this issue.

**Comment by nikmartin** [comment]
This is still happening for me after building with 0.6.7.  I deleted all the plugins, updated  package.json to install deploy plugin 0.6.7 then rebuilt the Android version. This downloaded all the plugins, and I verified that the deploy plugin had in fact updated. Extract still errors with the exact same message as​ above.

**Comment by yunho2141** [comment]
I also have same problem.

global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.3.0

local packages:

    @ionic/cli-plugin-cordova : 1.3.0
    @ionic/cli-plugin-ionic1  : 1.3.0
    Cordova Platforms         : android 6.2.3 ios 4.4.0
    Ionic Framework           : unknown

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.8

**Comment by tumbl3w33d** [comment]
@Fuiste I guess it's worth reopening this, as there are a few confirmations here already that your change didn't solve the issue, unfortunately.

**Comment by niallr12** [comment]
I am also experiencing the same problem.

**Comment by ashishtilara** [comment]
+1

**Comment by nikmartin** [comment]
FYI I was able to get this working by removing the platform, deleting the platforms directory, then adding them back and building.

**Comment by ztecharoberts** [comment]
This is still an issue for me.

i get this error 

cd: /data/user/0/com/app_c5f63b77-a7eb-40a5-8794-70bc40c39ff5/assets: Not a directory

**Comment by ztecharoberts** [comment]
Can someone check my pull request and make sure it works for others? I just tested locally on my own app and it seems to work.

**Comment by betatools** [comment]
I get the same error. Removing the platform and adding it again didn't fix it. 

cli packages:

    @ionic/cli-plugin-cordova       : 1.5.0 (/Users/jakob/Code/equipo/app/node_modules/@ionic/cli-plugin-cordova)
    @ionic/cli-plugin-ionic-angular : 1.4.0 (/Users/jakob/Code/equipo/app/node_modules/@ionic/cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (/Users/jakob/Code/equipo/app/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (/Users/jakob/Code/equipo/app/node_modules/ionic)

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.0
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy        : 1.9.1 
    ios-sim           : 6.0.0 
    npm               : 3.10.10

**Comment by martinchamrad** [comment]
Hi, getting the same error after upgrading to CLI 3.8.x 
Unzip error /data/data/com.tribelabs.tribe/app_4672b50e-a490-4ac5-a8c3-ab8cee536a7c/css/awlert.css: open failed: ENOTDIR (Not a directory)

What to do? Thx

**Comment by reggiejr** [comment]
I get different error messages at different times. Tried remove/add platform but it did not help. Using "ionic-plugin-deploy": "^0.6.7"

Error extracting update: /data/user/0/[APP_NAME]/app_fd3a6f14-e45d-4f6a-bc0c-7d4ee03d457e/**assets/data**: open failed: ENOTDIR (Not a directory)

Error extracting update: /data/user/0/[APP_NAME/app_2f52d3b5-d7aa-46fa-8d8c-3b3683099693/**build/0.js**: open failed: ENOTDIR (Not a directory)
-------------------------------
    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.13 
    Node              : v6.9.5
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b

**Comment by opiispanen** [comment]
Is there anything new regarding this problem?

I am experiencing this problem too after updating the CLI.
