### ISSUE TITLE
`getSnapshots()` always returns empty array

### ISSUE THREAD

**Issue by emcniece** [driftyco/ionic-plugin-deploy#123]
As per the title, my attempts to get a UUID list always returns an empty array.

I have followed http://docs.ionic.io/services/deploy/ for setup, and all of my channels in https://apps.ionic.io/app/123456/deploy have multiple uploads.

Running with `ionic run android -lcs`:

```js
import { Component } from '@angular/core';
import { Deploy } from '@ionic/cloud-angular';

@Component({
  selector: 'page-help-deploy-channel',
  templateUrl: 'deploy-channel.html',
})
export class DeployChannelPage {
  constructor(public deploy: Deploy) {

    console.log( this.deploy)
    if(this.deploy.getSnapshots){
      this.deploy.channel = 'dev'; // also tried 'production' and 'staging'
      this.deploy.getSnapshots().then((snapshots) => {
        // snapshots will be an array of snapshot uuids
        console.log(snapshots);
      });
    }
  }
}
```

`snapshots` is always `[]`. `this.deploy.check().then((snapshotAvailable: boolean)` does result in `snapshotAvailable` being `true` though, for all channels.  I don't see any web requests happening from the Network tab in the Chrome inspector. Am I doing something wrong?

**Comment by tumbl3w33d** [comment]
`getSnapshots()` lists locally installed snapshots, not those available in the cloud. It's initially empty, after you installed the app (e.g. via `ionic run`, using adb install,...). After you executed a deploy process (i.e., extracted a downloaded snapshot), this list is not empty anymore.

**Comment by emcniece** [comment]
@tumbl3w33d aha, thank you - that makes sense.
