### ISSUE TITLE
Build fail on iOS

### ISSUE THREAD

**Issue by enricodeleo** [driftyco/ionic-plugin-deploy#13]
Hi!
I'd really like to use ionic services instead of build my own "hot deploy" service, but I'm having a pain building the app for iOS.
When I install this plugin I get duplicate symbol errors. like `duplicate symbol _OBJC_IVAR_$_SSZipArchive._path` (I can past the entire log if needed).
I think it could be caused by the cordova-plugin-zip plugin, is there any way to solve? 

Thank you!

**Comment by conor-mac-aoidh** [comment]
+1 I've noticed this issue also. And my application requires cordova-plugin-zip, which means I can't use ionic-plugin-deploy for the moment.

**Comment by herman1vdb** [comment]
+1 Me too

**Comment by phonic** [comment]
Same problem here! Ionic deploy isn't working when cordova-plugin-zip is also used within the app. 

I've made an gulp task (with the [npm xcode](https://www.npmjs.com/package/xcode)) to clean up the duplicated xcodeproj-references. The app is running fine on newer ios devices, but unfortunately it does not, when running on older devices like ipad 3, iphone 5 etc - I get no callback from ionic.extract method, the extraction process logs only with "Zip Extraction: inf%" messageas in xcode. So, problem remains :(

Why don't you add a plugin-dependency for cordova-plugin-zip? Its very important to us, to get this bug fixed as soon as possible.

**Comment by ericb** [comment]
Hey everyone, this is been a long-outstanding issue that we can finally do something about with the latest cordova release (cocoapods support, yay! 👍). I've just started a new issue #107 please follow that for updates.
