### ISSUE TITLE
NSNumber in Objective C

### ISSUE THREAD

**Issue by violet7** [driftyco/ionic-plugin-deploy#31]
please fix NSNumber compare in IonicDeploy.m

**Comment by ericb** [comment]
@violet7 Could you provide a little more context?

**Comment by violet7** [comment]
For example: ionic-plugin-deploy-master/src/ios/IonicDeploy.m line 134
if (compatible != [NSNumber numberWithBool:YES]) addr compare?

**Comment by ericb** [comment]
@violet7 I'm not sure what you're expecting to change there. XCode shows no warnings or errors there. As far as I can tell it's a valid comparison.
