### ISSUE TITLE
Issues after native application update on iOS

### ISSUE THREAD

**Issue by rkistner** [driftyco/ionic-plugin-deploy#34]
When updating the native application on iOS, Ionic Deploy is not consistent in how it handles previously downloaded updates.

1. Install native application version 1.0.
2. Download update 1.1 via Ionic Deploy.
3. Install native application update 1.2.
4. On first start, Ionic Deploy detects the application update, and sets `self.ignore_deploy = true`. `uuid: ""`, `ignore_deploy: true`, `ignore_version: ""`
5. Check for Ionic Deploy updates.
6. Ionic Deploy finds 1.1 on the server, but sees it is already downloaded. It calls `doRedirect`.
7. `doRedirect` sees `self.ignore_deploy` is true, so it ignores the redirect request. However, no JavaScript callback is fired in this case, so the app thinks it's still busy downloading **(first issue)**.
8. Restart the app. Now update check works and reports no update. `uuid: ""`, `ignore_deploy: true`, `ignore_version: "xxx"`
9. Restart the app again. DON'T check for updates this time. `uuid: ""`, `ignore_deploy: true`, `ignore_version: ""`
10. Restart a last time, and check for updates. Now the app loads version 1.1 that was previously downloaded **(second issue)**. `uuid: ""`, `ignore_deploy: false`, `ignore_version: ""`.

The first issue is mildly annoying (my update progress indicator keeps on spinning). The second issue is however more serious.

It does seem like I can prevent all of the above by setting a maximum versions for each deploy, or perhaps by always deploying a new version before releasing a new native update. As far as I can see the application never tries to switch to a downloaded version unless the server tells it to.

I did not test any of this on Android.

**Comment by ericb** [comment]
What callback are you referring to for the first issue?
As for the 2nd, it shouldn't ever download the update again if it's already on the device.

**Comment by rkistner** [comment]
For the first issue, I'm triggering the updates from JavaScript (not using the watch function), with something like this:

```
var checking = true;
return $ionicDeploy.check().then(function(update) {
    if (update) {
        return $ionicDeploy.download().then(function() {
            return $ionicDeploy.extract().then(function() {
                return $ionicDeploy.load();
            });
        });
    }
}).finally(function() {
    // This is never reached in the case of the first issue
    checking = false;
});
```

I did not confirm at which promise in that chain it is stuck, but I assume it's the `$ionicDeploy.check()` one.

For the second issue, I can confirm that it is never downloading the update again. The problem is that switching from the new bundled app (HTML/JS bundled with the native package) to a previously downloaded one (typically older than the bundled app) is inconsistent.

**Comment by ericb** [comment]
I'm still unclear as to what you mean by the 2nd issue, but for the first, I think your issue may be more related to the way you're returning a promise overall.

As a side note, are you using the [ionic-platform-web-client](https://github.com/driftyco/ionic-platform-web-client) or are still on the deprecated [ionic-service-push-client](https://github.com/driftyco/ionic-service-push-client)?

**Comment by rkistner** [comment]
I can get a different but related issue as follows:

1. Install native app from scratch, let's call it 1.0.
2. Deploy 1.1 via ionic deploy, and update to this version.
3. Deploy 1.2 via ionic deploy, and update to this version. No issue so far.
4. Revert to 1.1, either via "roll back to here" or by switch to a channel with the older version. Ionic switches to this older version, but since it doesn't go through the `extract` call again (it was already downloaded and extracted), it doesn't call `[self updateVersionLabel:NOTHING_TO_IGNORE];`.
5. Restart the app. `initVersionChecks` detects a mismatch between the `ionicdeploy_version_label` (still the uuid of 1.1) stored in preferences, and the one constructed from the stored `uuid` (the uuid of 1.2). This sets `self.ignore_deploy = true`, and loads the bundled app (1.0).
6. Subsequent restarts will usually load the bundled app, sometimes switch to 1.1 after an update check, then revert back to the bundled 1.0 after the next restart.

**Comment by rkistner** [comment]
I'm still using the deprecated ionic-service-deploy. However, the cause of the first issue is definitely in the native part of `ionic-plugin-deploy`, not in the JavaScript service. The native `download` method never does a `sendPluginResult` call after reaching this point: https://github.com/driftyco/ionic-plugin-deploy/blob/master/src/ios/IonicDeploy.m#L189

For the second issue, see my last comment. It's not exactly the same, but very similar, and easier to reproduce.

**Comment by ericb** [comment]
Ok, thanks for the info @rkistner . I'm currently working on some other deploy updates so I'll look into this more closely next week and provide an update.

**Comment by rkistner** [comment]
Thanks, looking forward to the updates.

**Comment by ericb** [comment]
@rkistner I'll be releasing an update to deploy shortly that should at least address *some*, if not all, of the issues you brought up. However you'll need to update to the new ionic-platform-web-client in order to correctly test.

**Comment by rkistner** [comment]
Thanks! I'll test soon.

**Comment by rkistner** [comment]
@ericb I can confirm that this solves the most important issues I had. I ran into two more issues, but I'll open separate issues for them.
