### ISSUE TITLE
check() function not work, only returning Ionic Deploy: no updates available

### ISSUE THREAD

**Issue by grapemix** [driftyco/ionic-plugin-deploy#36]
Hi,

First of all, I think this feature is awesome and I would really like to use this feature. Thanks for your work.

I am following the tutorial in http://docs.ionic.io/docs/deploy-install, but I cannot make the deployment work. Ideally, my app can check for update at every startup and update the app if new version is available. So besides of the button example in the tutorial, I also try the following snippet:

var deploy = new Ionic.Deploy();

// Check for updates
deploy.check().then(function(response) {
  // response will be true/false
  if (response) {
    // Download the updates
    deploy.download().then(function() {
      // Extract the updates
      deploy.extract().then(function() {
        // Load the updated version
        deploy.load();
      }, function(error) {
        // Error extracting
      }, function(progress) {
        // Do something with the zip extraction progress
        console.log(progress);
      });
    }, function(error) {
      // Error downloading the updates
    }, function(progress) {
      // Do something with the download progress
      console.log(progress);
    });
  }
}, function(error) {
  // Error checking for updates
});

But both experiment return 'Ionic Deploy: no updates available'.
I double check the ionic.io's webinterface,  the deploy is there. 
I also tried to switch to another channel by 'deploy.setChannel("dev");', but still not working.
I am also testing with updating the app without checking, it returns'Ionic Deploy: Update Success!', but the app is not updating.
I tried to click the update button with and without restating the app, but still not working.

I tried to call deploy.getVersions().then(function(r){console.log(r);}); , it returns'binary_version: "1.0.6"deploy_uuid: "NO_DEPLOY_AVAILABLE"'.

I tried to put config.xml inside www/, still not working.

Any ideas?

Thanks,

**Comment by ericb** [comment]
Something is amiss. `getVersions` should return an array, not an object. The response you got was something you get from `info`. I would suggest removing and adding the platform again, and also, make sure that you have the latest version of the ionic-platform-web-client as well as this plugin.
