### ISSUE TITLE
Reverts to bundled app if extract fails (iOS)

### ISSUE THREAD

**Issue by rkistner** [driftyco/ionic-plugin-deploy#37]
To simplify the example, say I have an Ionic application that is bundled with version 1.0 of my app. Version 1.1 was already downloaded via Ionic Deploy, and is the currently active version on the device. Version 1.2 was just released via Ionic Deploy.

Now if update 1.2 is **downloaded, but not extracted**, the update `uuid` is saved, but `ionicdeploy_version_label` not. On the next boot, it detects a mismatch between the version labels, and reverts to the bundled app (1.0), instead of the previously downloaded update (1.1).

This is an edge case, and should not typically happen in normal circumstances. However, it could happen if for example the app crashes between the `download()` and `extract()` calls.

This was tested with ionic-plugin-deploy 0.4.0 and ionic-platform-web-client 0.2.0 on iOS.

**Comment by michael-may** [comment]
This sounds similar to an issue we are seeing, except the update appears to download and extract successfully (all changes are reflected).

Once the user opens the app a second time, it has reverted to the bundled version.

Once the user opens the app a third time, they are prompted to do an update which completes immediately.

After this point the update sticks until the next version is pushed and the process repeats.

**Comment by rkistner** [comment]
@michael-may Are you using version 0.4.0 of the plugin? I had some issues like that which were solved when upgrading from 0.3.0 to 0.4.0.

**Comment by michael-may** [comment]
@rkistner 
Looks to be:
0.4.0 of ionic-plugin-deploy
0.2.0 of ionic-platform-web-client

**Comment by rkistner** [comment]
@michael-may I've also experienced issues similar to what you describe now, basically making ionic-deploy unusable :( Haven't done detailed checks into what exactly the issue is yet.

**Comment by michael-may** [comment]
@rkistner 
The weird thing is that it only appears to be happening in iOS. Android handles it just fine. I'll see if I can dig into the logs and find something that might point us somewhere.

**Comment by jskrzypek** [comment]
@rkistner @michael-may 

We are seeing an issue with a very similar pattern, and we think might stem from the same bug. Currently if you look at @michael-may 's logs above, you see that there's only one place where the line "updating version label" is being logged, which is coming from [`IonicDeploy.m:76`](https://github.com/driftyco/ionic-plugin-deploy/blob/master/src/ios/IonicDeploy.m#L76).

I think this is not being called in the extract method on the first run, where it should, and what's happening is that `uuid` gets updated but the `ionicdeploy_version_label` does not, so on the application load the `initVersionChecks` treats `uuid` as a bad version and ignores it.

We made the following change and it seems to be working, inserting the line
```objectiveC
     [self updateVersionLabel:NOTHING_TO_IGNORE];
```
following [`IonicDeploy.m:241`](https://github.com/driftyco/ionic-plugin-deploy/blob/master/src/ios/IonicDeploy.m#L241)


This is the resulting extract method. I'm pretty sure this is a good fix but I don't really know objectiveC so I'm not 100%. I'm happy to make a PR, if desired. Credit goes to @ghaiat for finding the fix.
 
```objectiveC
(void) extract:(CDVInvokedUrlCommand *)command {
    self.appId = [command.arguments objectAtIndex:0];

    dispatch_async(self.serialQueue, ^{
        self.callbackId = command.callbackId;
        self.ignore_deploy = false;

        NSString *upstream_uuid = [[NSUserDefaults standardUserDefaults] objectForKey:@"upstream_uuid"];

        if(upstream_uuid != nil && [self hasVersion:upstream_uuid]) {
            [self updateVersionLabel:NOTHING_TO_IGNORE];
            [self.commandDelegate sendPluginResult:[CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsString:@"done"] callbackId:self.callbackId];
        } else {
            NSArray *paths = NSSearchPathForDirectoriesInDomains(NSApplicationSupportDirectory, NSUserDomainMask, YES);
            NSString *libraryDirectory = [paths objectAtIndex:0];

            NSString *uuid = [[NSUserDefaults standardUserDefaults] objectForKey:@"uuid"];

            NSString *filePath = [NSString stringWithFormat:@"%@/%@", libraryDirectory, @"www.zip"];
            NSString *extractPath = [NSString stringWithFormat:@"%@/%@/", libraryDirectory, uuid];

            NSLog(@"Path for zip file: %@", filePath);

            NSLog(@"Unzipping...");

            [SSZipArchive unzipFileAtPath:filePath toDestination:extractPath delegate:self];
            [self saveVersion:upstream_uuid];
            [self excludeVersionFromBackup:uuid];
            [self updateVersionLabel:NOTHING_TO_IGNORE];  // This is the added line.
            BOOL success = [[NSFileManager defaultManager] removeItemAtPath:filePath error:nil];
            NSLog(@"Unzipped...");
            NSLog(@"Removing www.zip %d", success);
        }
    });
}
```

**Comment by jskrzypek** [comment]
Also this looks like the same behavior as #21

**Comment by michael-may** [comment]
@jskrzypek 
Looks like this change did the trick in our project as well.

**Comment by jskrzypek** [comment]
nice! I'm submitting a PR now

**Comment by xlozinguez** [comment]
:+1: that fixes it for us too

**Comment by ericb** [comment]
Thanks for the PR @jskrzypek
