### ISSUE TITLE
Deploy Ignored

### ISSUE THREAD

**Issue by marnoldpalmer1** [driftyco/ionic-plugin-deploy#38]
Having issues getting Deploy up and running on my project on IOS. In Xcode output window, I get this series of outputs:
 
2015-10-27 22:37:42.503 App[14834:4704599] VERSION LABEL: 0.0.1:1445999841:
2015-10-27 22:37:42.503 App[14834:4704599] updating version label

Which then leads to these outputs: 

2015-10-27 22:37:43.229 App[14834:4704599] uuid is: 
2015-10-27 22:37:43.230 App[14834:4704599] ignore deploy
2015-10-27 22:37:43.230 App[14834:4704599] ignore version: 

Judging by the fact that it's ignoring deploy, and refuses to give up the uuid, I'm assuming I have something set up wrong. I've installed the web platform, and had no issues installing the deploy plugin. Is there something I'm missing? is anyone else having this same issue?

**Comment by ericb** [comment]
when you install an app on the device or emulator, deploy will ignore the current deploy uuid (if there is one) -- this prevents your development updates from being shown unless you do a deploy on every change.

**Comment by MattArnold93** [comment]
Can you explain what you mean by a deploy on every change? Do you mean that it will ignore deploy unless there is a deploy available?
