### ISSUE TITLE
Plugin says "no update" although http request says "update available"

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-plugin-deploy#41]
Sometimes I encounter the following situation (on Android).

From my console:

    Ionic Deploy: Update available: false

While this is the response of the http request:

    {
	    "compatible_binary": true,
	    "update_available": true,
	    "update": {
		    "uuid": "7f26bf4c84...6bc59ebac",
		    "url": "https://ionic-apps.s3.amazonaws.com/99aYo1T...2c7qiS%2BbOY6U%3D&Expires=1446...05&AWSAccessKeyId=AKIAJ...D34A"
	    }
    }

Obviously the console and the request don't agree. What could cause this?

**Comment by ericb** [comment]
We ignore deploys that are actively on a device when you install the app on your device (this prevents you from having to constantly deploy to see your changes in development -- otherwise you would make changes, but would continue to only see the last active deploy on the device)

**Comment by piotrowski** [comment]
Totally makes sense, thanks.

Couldn't this be indicated via a console.log to make this transparent? 
Then we could really understand what is happening and be sure that nothing is going wrong (and don't even have to look at the http response body to check.)
