### ISSUE TITLE
ionic plugin add ionic-plugin-deploy fails

### ISSUE THREAD

**Issue by siddiq** [driftyco/ionic-plugin-deploy#43]
As documented here: http://docs.ionic.io/docs/deploy-install
The following command fails.

    $ ionic plugin add ionic-plugin-deploy

    Native thread-sleep not available.
    This will result in much slower performance, but it will still work.
    You should re-install spawn-sync or upgrade to the lastest version of node if possible.
    Check /home/siddiq/.local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cross-spawn/node_modules/spawn-sync/error.log for more details
    Updated the hooks directory to have execute permissions
    Fetching plugin "ionic-plugin-deploy" via npm
    npm http GET https://registry.npmjs.org/ionic-plugin-deploy
    npm http 401 https://registry.npmjs.org/ionic-plugin-deploy
    TypeError: Cannot read property 'latest' of undefined
        at next (/home/siddiq/.local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache.js:687:35)
        at /home/siddiq/.local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache.js:675:5
        at saved (/home/siddiq/.local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
        at /home/siddiq/.local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
        at Object.oncomplete (fs.js:107:15)

**Comment by ericb** [comment]
This looks like an issue with something on your machine or network. That, or perhaps you've got some local permissions issues / outdated npm install.

**Comment by siddiq** [comment]
$ npm --version
    2.13.4

So I installed from github url directly.

    $ ionic plugin add https://github.com/driftyco/ionic-plugin-deploy.git

**Comment by Fuiste** [comment]
Closing as this issue is with npm, rather than the deploy plugin.
