### ISSUE TITLE
How to get metadata for available update?

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-plugin-deploy#47]
I see there is 'getMetadata()' that expects a uuid of the deploy you want to get the metadata for. But how can I get this uuid for the next available update? 

I want to show changelogs and other metadata to the user before he updates, and this seems like it was intended for this usecase, but I can't seem to connect the dots :/

**Comment by ericb** [comment]
Yea that was definitely one of the use cases. If you don't supply a uuid it will use the "last known available update". So maybe to put that more simply, you can do a `check()` and if that returns that there is an update, you can then follow up with a `getMetadata()` call without passing a uuid. This will give you the metadata for the pending update.

**Comment by piotrowski** [comment]
Yes, that works. Thank you.

This should probably be included more clearly in the docs, just now saw that it is already mentioned in the comments of http://docs.ionic.io/docs/deploy-usage#section-metadata

**Comment by ericb** [comment]
Agreed. I'll make a better note of it now.
