### ISSUE TITLE
iOS status bar overlaps Ionic app after deploy update

### ISSUE THREAD

**Issue by jwbuitenhuis** [driftyco/ionic-plugin-deploy#48]
I'm developing an Ionic 2 app, and I've used Ionic Deploy to dynamically update. The update works, but after the update the app doesn't leave space for the status bar. Before updating:

![image](https://cloud.githubusercontent.com/assets/2378530/11333805/5730150e-91c8-11e5-8128-c45d01cee841.png)

After:
![image](https://cloud.githubusercontent.com/assets/2378530/11333843/958e6bfc-91c8-11e5-96e0-0c904cb35064.png)

I'm updating using:
    this.deploy = new Ionic.Deploy();
    this.deploy.update().then(res => { ... }

**Comment by ericb** [comment]
This would be something in your app code, missing files, or maybe even a include path issue. Deploy just facilitates loading up a new app directory. You may also want to check that you don't have any javascript styling/positioning happening before all the elements have been dumped.

**Comment by jwbuitenhuis** [comment]
Thanks for responding.

It looks like after loading an update, the class "platform-cordova" is missing from the html body tag.

If I add this to my app constructor the layout looks fine:
    if (document.body.className.indexOf('platform-cordova') === -1)
        document.body.className = document.body.className + " platform-cordova";

I'm not doing any styling/include that would logically influence that class. Any ideas on how to debug further?
