### ISSUE TITLE
Binary 0.2.4 says update available although last deploy is binary equivalent 0.2.3

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-plugin-deploy#49]
I have a deploy that is marked "iOS Binary Version - equivalent" to "0.2.3" on apps.ionic.io. Now I built a new version "0.2.4" in Xcode. Running this version in the simulator and also on a real device Ionic Deploy tells me that an update is available (the "0.2.3" that is currently deployed) and I can update to it.

Wouldn't it make sense to add this as an additional check: "if binary equivalent is equal **or lower** than current binary version"?

(I could temporarily fix this by changing the "equivalent" version to "0.2.4" - but this of course only worked on my test environment. On live I would have been forced to `ionic upload` something just to make sure the obviously newer binary version doesn't get an older deploy as an update).

**Comment by martyzz1** [comment]
+1

**Comment by Fuiste** [comment]
You can use the `maximum` version to accomplish this functionality.
