### ISSUE TITLE
"unable to check for updates" in version 0.4.1

### ISSUE THREAD

**Issue by yossi-shasho** [driftyco/ionic-plugin-deploy#52]
After upgrading from 0.3.0 to 0.4.1, the feature seems broken.
I have also updated `ionic-platform-web-client` to the latest.

Here's the log dump:
```
uuid is: 
channel is: staging
In Finally
JSON Error: (null)
Response: (null)
unable to check for updates
** -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:completion:] ** unhandled action -> <FBSSceneSnapshotAction: 0x14e6cf590> {
    handler = remote;
    info = <BSSettings: 0x14f90f750> {
        (1) = 5;
    };
```

**Comment by ericb** [comment]
0.4.1 has been out for months, so I think it's more likely that there is something misconfigured in your app. Are you sure you're not being blocked by something like iOS Security Transport Protocol?

**Comment by yossi-shasho** [comment]
I couldn't solve it, so I simply downgraded to the older version. Moreover, there's hardly any code we wrote to wrap the feature, it simply wouldn't work.
