### ISSUE TITLE
Android Hardware Back Button stops working

### ISSUE THREAD

**Issue by arashb31** [driftyco/ionic-plugin-deploy#53]
When updating to a new version from Ionic Deploy, the hardware back button doesn't seem to work anymore for navigating.

This issue happens on Nexus devices (Nexus 4,5,6, 6P) running latest available Android versions for them.

The hardware back button continues to work for Cordova plugins like the InAppBrowser, for example.

**Comment by zhaoxinpeng** [comment]
I have the same issue

**Comment by NickMele** [comment]
I am also wondering what the status of this is, we are encountering the same issues. Whenever a new deploy is made and the Android app gets updated, the back button stops working until you kill the app.

**Comment by NickMele** [comment]
I am seeing this consistently on a Samsung Galaxy Note 3 and Note 5, if that helps at all.

**Comment by REBOOTERS** [comment]
` webView.loadUrlIntoView(deploy_url, recreatePlugins);

    webView.clearHistory();`

add clearHistory()  ,the hardware back button will work

**Comment by Fuiste** [comment]
I've just published version `0.6.5` of the plugin which addresses this issue.  Let me know if you have any trouble.
