### ISSUE TITLE
Deploy changes non permanent on IOS

### ISSUE THREAD

**Issue by Pulstarter** [driftyco/ionic-plugin-deploy#54]
Hi!

I have an issue with the deploy plugin. I am able to download and install the update via deploy, but when I kill the app and restart it, the version was the previous to the update and never updates again. I am installing the app on a device (IOS 9.2.1) with Xcode. I have tested it on simulator with 9.2 and 8.4 and the behaviour is the same. I haven't tested on Android.

Here is some info:

$ ionic plugin list
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-splashscreen 3.1.0 "Splashscreen"
cordova-plugin-statusbar 2.1.1 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
ionic-plugin-deploy 0.4.1 "IonicDeploy"
ionic-plugin-keyboard 1.0.8 "Keyboard"

$ ionic info
Your system information:
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.2.1 Build version 7C1002 

I think I have the correct versions. This could be an issue with localstorage or something similar? Any indication will be appreciated.

The full process is:

1- Build the app with 'ionic build ios'. (1.0)
2- Install on a device with Xcode.
3- Make some changes on the code.
4- Run "ionic upload --note " something" ' (1.1)
5- Enter to deploy section and deploy the update.
6- The device update to 1.1
7- Kill the app and restart
8- The device is now on 1.0 and does not find updates.

Best regards,
Iker

**Comment by ericb** [comment]
Can you use the `info` method to verify the uuid of the deploy is correct?

**Comment by Pulstarter** [comment]
Hi!

The info method returns an [object Object] that I don't know how to retrieve the data. Can you please tell me which info do you need?

Here I have some more info:

The base version is 0.2.3, and I want to update to 0.2.4. The app updates ok, but always start with this string:

`VERSION LABEL: 0.2.3:1457101836:d5ee03b2e21611e5898e52a81a3c292d`

I have this logs too:

```
2016-03-04 15:42:43.196 ocioescort[14072:150700] version is: 0.2.3
2016-03-04 15:42:43.196 ocioescort[14072:150700] uuid is: d5ee03b2e21611e5898e52a81a3c292d
2016-03-04 15:42:43.197 ocioescort[14072:150700] channel is: production
2016-03-04 15:42:43.197 ocioescort[14072:150700] In Finally
2016-03-04 15:42:43.197 ocioescort[14072:150700] JSON Error: (null)
2016-03-04 15:42:43.197 ocioescort[14072:150700] Response: (null)
2016-03-04 15:42:43.197 ocioescort[14072:150700] compatible: True
2016-03-04 15:42:43.197 ocioescort[14072:150700] available: True
2016-03-04 15:42:43.198 ocioescort[14072:150700] update uuid: d5ee03b2e21611e5898e52a81a3c292d
2016-03-04 15:42:43.198 ocioescort[14072:150700] update is false
2016-03-04 15:42:43.201 ocioescort[14072:150614] Ionic Deploy: no updates available
```

The version line never changes. The d5ee03b2e21611e5898e52a81a3c292d uuid is for the 0.2.4, not the 0.2.3.

I dont know if this could help.

Best regards,
Iker

**Comment by Pulstarter** [comment]
Hi!

If I call load() method the deploy works as expected, but I found that sometimes this freezes the app. I put it into a timeout function with 100ms and it works fine now.

Do this have to work without the load method?

Regards,
Iker

**Comment by Pulstarter** [comment]
I finally found that the freeze problem is related with cordova 4.0.1 and IOS. The 4.1.0 version fixes the problem:

[Cordova 4.1.0](http://cordova.apache.org/announcements/2016/03/02/ios-4.1.0.html)

Regards.
