### ISSUE TITLE
Cordova 6.0.0 [self.webView loadRequest] is not defined.

### ISSUE THREAD

**Issue by xishuango0o0** [driftyco/ionic-plugin-deploy#55]
When I use cordova at version 6.0.0 ,
has error on **Plugins/ionic-plugin-deploy/IonicDeploy.m:345:27: No visible @interface for 'UIView' declares the selector 'loadRequest:'**
can you fix it?

**Comment by ericb** [comment]
This is fixed with #50 and will be pulled into the next update (this week I believe)
