### ISSUE TITLE
iOS stack on ignore version: NO_DEPLOY_LABEL (fresh install)

### ISSUE THREAD

**Issue by deliverymanager** [driftyco/ionic-plugin-deploy#64]
After creating a fresh ionic project, using the iOS platform 3.8.0 (which is the default in ionic start) the problem I am describing did not exist. The problem exists in iOS platform 4.0.1 and 4.1.0.

The problem is that the simulator gets stack in the splash screen and the logs are showing what appears in the image below.

Reproduce with the steps:
ionic start testDeploy
cd testDeploy
ionic platform remove ios
ionic platform add ios
ionic add ionic-platform-web-client
ionic io init
ionic plugin add ionic-plugin-deploy
ionic run ios

![screenshot 2016-04-25 14 23 40](https://cloud.githubusercontent.com/assets/4013348/14782333/680f2714-0af1-11e6-9ad5-9a0dd07f344e.png)
![screenshot 2016-04-25 14 24 03](https://cloud.githubusercontent.com/assets/4013348/14782332/680efb54-0af1-11e6-9d09-375bcf0d7ab0.png)

**Comment by deliverymanager** [comment]
I have also tested the ios version 4.0.0 and the problem still exists there.
I have tested the cordova ios version 3.9.2 and the problem doesn't exist there.
![screenshot 2016-04-25 14 49 21](https://cloud.githubusercontent.com/assets/4013348/14782918/f3b77426-0af4-11e6-8cab-967f5c1d4e3a.png)

**Comment by ericb** [comment]
NO_DEPLOY_LABEL is a normal label when there is nothing deployed to the device. You've either got an outdated version of a plugin or some other error in your application.

**Comment by deliverymanager** [comment]
Thank you for your answer.
The reason for the issue that you suggested which is the outdated version of a plugin is little strange because I have tested it on a fresh installation.
Did you see the patern of the cordova ios version?
It works on 3.9.2 and not on 4.0.1 and above.

Where do you beleive I should check for the outaded update?
Thank you!

**Comment by deliverymanager** [comment]
@ericb The problem of **iOS getting stack on the splash screen with the deploy plugin** is very easily reproducible on a fresh / clean ionic project without any additional plugins other than the basic.
Can you please at least confirm the issue?
My configuration was the following

![screenshot 2016-04-26 11 23 06](https://cloud.githubusercontent.com/assets/4013348/14811654/c083fbe4-0ba1-11e6-9cd8-65882bea7717.png)

and the logs from xCode where the app is getting stack on the splash screen are the following:
![screenshot 2016-04-26 11 27 57](https://cloud.githubusercontent.com/assets/4013348/14811715/072786c4-0ba2-11e6-8ab7-7e9324023d7d.png)

**Comment by deliverymanager** [comment]
I can confirm that the version 0.5.4 has resolved the problem of the iOS app getting stack on the splash screen.
Thank you!

**Comment by jackvial** [comment]
I was having the same issue but with version 0.5.4. Rolling back to 0.5.0 of the plugin fixed it for me.

**Comment by deliverymanager** [comment]
What version of cordova ios do you use?

**Comment by Fuiste** [comment]
@jackvial I can take a look into it, I just need your `cordova-ios` version, iOS version, and `ionic-platform-web-client` version.
