### ISSUE TITLE
iOS gets stuck on splash screen

### ISSUE THREAD

**Issue by jackvial** [driftyco/ionic-plugin-deploy#65]
With v0.5.4 of the plugin the app gets stuck on the splash screen when running on my device (iPhone 5, iOS 9.3.1). I noticed a few iOS specific changes in the recent commits, so I installed v0.5.0 which worked for me without any issues.

**Comment by jackvial** [comment]
Update:

I tried v0.5.3 and that works well on both iOS and android. It looks like commit 0c069fd9b386ad1a5e09f246ad5871feaf2acfa4 is causing the app to get stuck on the splash screen on iOS. At least that is the case for me anyway.

**Comment by Fuiste** [comment]
@jackvial I'll need a couple things to start debugging what's going on here.

* Your `cordova-ios` version
* The iOS version on your device
* The version of the `ionic-platform-web-client` you're running.

**Comment by Fuiste** [comment]
@jackvial whoops, accidentally copied my reply from the other issue over to this one.  Anyways, I do still need your `cordova-ios` version.

In addition, are you seeing anything in the logs suggesting an error when the app hangs?  I ask cause I"m not able to reproduce this on `cordova-ios` 3.8.0, 3.9.2, or 4.1.0.

**Comment by rdavono** [comment]
I have the same problem with Cordova CLI 6.1.1 and iOS 4.1.1

**Comment by rdavono** [comment]
More information: Simulator works fine, but not on actual device.

This may be a WKWebView issue: https://issues.apache.org/jira/browse/CB-10237

The hot code push plugin seems to have a workaround: https://github.com/nordnet/cordova-hot-code-push/issues/85

**Comment by GoArabGo** [comment]
i have the same problem and i use phonegap build

**Comment by pauly4it** [comment]
Just wanted to add some of my own experiences here:

With cordova-ios v3.9.2, I can confirm that the code in PR #59 works properly. ionic-plugin-deploy v0.5.4 (https://github.com/driftyco/ionic-plugin-deploy/tree/v0.5.4) does not work with cordova-ios v3.9.2 and causes the splash screen to get stuck.

We can't update cordova-ios due to other plugin compatibility, so we're going to stick with pulling in https://github.com/driftyco/ionic-plugin-deploy#42eeec1110953e1c571ab66af91bdca7a6da63b8 into our projects for now.

**Comment by EyalSeagull** [comment]
I'm not sure if it is the same problem, but I've experienced crashes the same way on iOS. Maybe issue #73 can help (I've changed manually IonicDeploy.m and it started working again).

**Comment by yossi-shasho** [comment]
+1.
0.5.6 gets stuck on splash screen on iOS. no JS resources are even loaded. see attached the console output in XCode
![screen shot 2016-06-23 at 3 00 23 pm](https://cloud.githubusercontent.com/assets/1956748/16302331/3e02e542-3953-11e6-9498-29666004fe11.png)

**Comment by deliverymanager** [comment]
You are running on cordova ios 3.9.2.
You should use the 4.1.1

**Comment by yossi-shasho** [comment]
that indeed solved it. But this should probably be stated in the documentation.

**Comment by Fuiste** [comment]
Marking solved as of the latest deploy plugin and Ionic CLI, which now defaults to a more modern `cordova-ios`.
