### ISSUE TITLE
reopen app for second time after rollback gets wrong version 

### ISSUE THREAD

**Issue by MarwaAbuEssa** [driftyco/ionic-plugin-deploy#67]
hi,

I'm using la tested Ionic-deploy plugin Version , using the following code :

 deploy.setChannel("dev");
            deploy.check().then(function(response) {
            // response will be true/false
            if (response) {
                // Download the updates
                deploy.download().then(function() {
                // Extract the updates
                deploy.extract().then(function() {
                    // Load the updated version
                 
                    deploy.load();
                    $ionicLoading.hide();
                }, function(error) {
                    // Error extracting
                }, function(progress) {
                    // Do something with the zip extraction progress
                       $ionicLoading.hide();
                       $rootScope.extractprogress = progress
                     $ionicLoading.show(
                           {
                               template: '<i class=" ion-loading-c"></i> ' + "One moment please...Exatracting <br>{{extractprogress}}%",
                               animation: 'fade-in',
                               showBackdrop: true,
                               maxWidth: 200,
                               showDelay: 0,
            
                           })
                           
                   //  deploy.load();
                    console.log(progress);
                });
                }, function(error) {
                // Error downloading the updates
                }, function(progress) {
                      $rootScope.progress = progress
                     $ionicLoading.show(
                           {
                               template: '<i class=" ion-loading-c"></i> ' + "A minor update is being applied to iRehearse. Downloading...<br>{{progress}}%",
                               animation: 'fade-in',
                               showBackdrop: true,
                               maxWidth: 200,
                               showDelay: 0,
            
                           })
                // Do something with the download progress
                console.log(progress);
                });
            }
            }, function(error) {
            // Error checking for updates
            });

now I had a build version 1.2.1 at android emulator & Mobile device, and do the following 
1- make update => upload it => set equivalent version to 1.2.2 => deploy => and done successfully
2- make update => upload it => set equivalent version to 1.2.3 => deploy => and done successfully
so now i had Version 1.2.3 running at my emulator & Mobile device
now rollback to version 1.2.2 => open the app => found version 1.2.2
the problem is after closing and reopening the app again => found version 1.2.1 :-1: 

- i checked the active version at the deployment channel => still found 1.2.2

so the problem is reopening the app for the second time after rolling back gets the last build version not the rolled back version

**Comment by Mohamed-Habshey** [comment]
:+1:  same here

**Comment by MarwaAbuEssa** [comment]
anyone ?

**Comment by troygilbert** [comment]
I've had a similar issue where my apps update to the latest version correctly but when the app relaunches at a later point it loads an old version, but Deploy.info() continues to report the latest version (maybe related?).

**Comment by MarwaAbuEssa** [comment]
i had upgraded ionic to 1.3.1(latest) at my app and the issue still exists :disappointed:

**Comment by troygilbert** [comment]
This was related to the ionic deploy plugin. Upgrade to at least 0.5.4 to fix it.

**Comment by MarwaAbuEssa** [comment]
thanks @troygilbert  but  i have a  deploy plugin version is 0.5.4  already

**Comment by Fuiste** [comment]
@MarwaAbuEssa can you confirm whether this issue still occurs as of version `0.6.3` of the plugin?

**Comment by MarwaAbuEssa** [comment]
@Fuiste  unfortunately Issue still exists :(

**Comment by sergioaok** [comment]
I'm also having this issue. Is there any way to fix ? Or a workaround?

**Comment by Fuiste** [comment]
Hey guys, just a quick update that I was able to reproduce the issue on my end.

I've pushed a new version of the plugin to fix this, `0.6.4`
