### ISSUE TITLE
Ionic Deploy: no updates available

### ISSUE THREAD

**Issue by hossam9995** [driftyco/ionic-plugin-deploy#69]
hello, 

I'am using ionic deploy plugin and i do every thing on this doc http://docs.ionic.io/docs/deploy-quick-start

but its always return for me Ionic Deploy: no updates available

i use the version and info function to return some information 

**check update function return all time**
`onic Deploy: no updates available`

**version function return **
` Array[0]length: 0__proto__: Array[0]`

**info function return** 
`Objectbinary_version: "0.0.1"deploy_uuid: "NO_DEPLOY_AVAILABLE"__proto__: Object
`
what i should to do to defined the uuid ? 

hint i use ionic 1 and i use cutsom strucure 
see the strucre https://github.com/diegonetto/generator-ionic

thanks alot

**Comment by ericb** [comment]
You'll need to give a little more information about what you're checking against. Have you deployed a version to the proper channel? Is the correct channel being used in the app itself? What about min/max/and equivalent versions for the deploy?

**Comment by hossam9995** [comment]
thanks for your reply ,, 
I'am set the channel in both ionic io dashboard and on the application  by use  `deploy.setChannel("production");`

and i set  equivalent versions to  `0.0.1`  and min to `0.0.1` and max to `0.0.4`

hint `0.0.1` version  it same to binary version that on the config.xml file

**Comment by ericb** [comment]
If you set the equivalent version to 0.0.1 and the device is running 0.0.1, it will not find an update. The equivalent version is used to specifically ignore updates because it could be the same version deployed to the app stores.

You should remove the equivalent version if it's not actually equivalent to the installed version (via apk/ipa or app stores)

**Comment by hossam9995** [comment]
hello again , 
I'am sorry for take long time to reply 
I already try with clear equivalent version and its the same result. 

I thing the issue when i type `ionic add ionic-platform-web-client`
it return that we can't change file `./www/js/app.js` becuse its not exsist (becuse i use the custom structure)
-> here i have to chose if i should to 
1- set `disable_modifications` to `true` 
2- change `./www/js/app.js` path to `./app/scripts/app.js`  to catch `app.js` file on my custom structure ..

if i chose the first solution, it should modify manually - > (how and what is it)? 
if i chose the second solution -> how can i change the app path to catch my custom structure path  ? 

The same thing also when i type `ionic io init` should change file `ionic.io.bundle.js`  not `ionic.io.bundle.min.js` that i use it on my app 

Regards, 
Nayef Hawa

**Comment by hossam9995** [comment]
finally , I got the solution 
only to set this code on ionic.io.bundle.js this code 

`   "IONIC_SETTINGS_STRING_START";
    var settings =
    {
        "app_id":"your id ",
        "api_key":"Your key",
        "disable_modifications":true,
        "dev_push":true
    };
    return {
        get: function(setting) {
            if (settings[setting]) {
                return settings[setting];
            }
            return null;
        }
    };
    "IONIC_SETTINGS_STRING_END";`

and then every thing will work fine for custom structure in my app 

 the application catch there is an update and i try to install it ,

,but the problem is after update files throw ionic io plugin  all  plugins not work no facebook login no google+ no sqllite ,, its like after catch update and download it ,, the plugins not work perfect ,?!
