### ISSUE TITLE
App seems to stuck when trying ionic deploy

### ISSUE THREAD

**Issue by warden1975** [driftyco/ionic-plugin-deploy#70]
When using xcode to install and run app to my device, it just hangs. Logs shows:

2016-05-20 10:51:30.817 ionXPlanner[1585:366489] VERSION LABEL: 1.3.0:1463712641:
2016-05-20 10:51:30.817 ionXPlanner[1585:366489] updating version label
2016-05-20 10:51:30.818 ionXPlanner[1585:366489] [CDVTimer][ionicdeploy] 2.484024ms
2016-05-20 10:51:30.819 ionXPlanner[1585:366489] [CDVTimer][TotalPluginStartup] 80.612004ms
2016-05-20 10:51:30.852 ionXPlanner[1585:366489] active
2016-05-20 10:51:31.014 ionXPlanner[1585:366489] uuid is: 
2016-05-20 10:51:31.015 ionXPlanner[1585:366489] ignore deploy
2016-05-20 10:51:31.015 ionXPlanner[1585:366489] ignore version:

Any ideas? Thanks in advance.

**Comment by tmdevde** [comment]
have exactly the same problem right now.

**Comment by mixersoft** [comment]
i'm not alone. whew! I thought I just messed up my project somehow.  I have the same errors from the xcode console, I even tried to build a clean project from scratch according the the `deploy quickstart` guide. It still hangs. But if I remove the plugin, the app loads fine, just no deploy 

```
ionic plugin remove ionic-plugin-deploy
ionic emulate
# app inits fine, just no deploy
```

My app used to work with deploy just fine, but today I upgraded to the latest release of `xcode` and also re-built the `platforms/ios` folder from scratch. Not sure if either of those steps caused the problem.

```
# from ionic info
Your system information:

Cordova CLI: 5.3.3
Gulp version:  Requiring external module coffee-script/register
Gulp local:   CLI version 3.9.1
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.0.0
Xcode version: Xcode 7.3 Build version 7D175 
```

**Comment by Fuiste** [comment]
Hey guys, what versions of the plugin and `cordova-ios` are you running when you get this issue?

**Comment by mixersoft** [comment]
I'm looking in `CordovaLib.xcodeproj` and it says `3.9.2` in the `VERSION` file. Is that the right place?

**Comment by Fuiste** [comment]
Yup, that's the `cordova-ios` version.  

Which version of the plugin are you running as well?

**Comment by mixersoft** [comment]
Sorry, I didn't see this until today. I'm using the latest version, here is the list from today:

```
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-camera 2.2.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-facebook4 1.7.1 "Facebook Connect"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.0 "SocialSharing"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
ionic-plugin-deploy 0.5.4 "IonicDeploy"
ionic-plugin-keyboard 2.0.1 "Keyboard"
```

**Comment by EyalSeagull** [comment]
Hi guys,

I'm not sure if it is the same problem, but I've experienced crashes the same way. Maybe issue #73 can help (I've changed manually IonicDeploy.m and it started working again).

Eyal

**Comment by FelixLC** [comment]
@Fuiste , I am facing the same issue with the following config:


```
#plugin list

cordova-plugin-camera 2.1.0 "Camera"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-email-composer 0.8.3 "EmailComposer"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-ios-base64 1.0.0 "iOSBase64"
cordova-plugin-print-pdf 4.0.0 "PrintPDF"
cordova-plugin-statusbar 2.1.1 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
de.appplant.cordova.plugin.printer 0.7.1 "Printer"
ionic-plugin-deploy 0.5.6 "IonicDeploy"
ionic-plugin-keyboard 1.0.8 "Keyboard"

#ionic info

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.8.4
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3.1 Build version 7D1014

#cordova ios
4.1.1
```

I tried downloading the deploy-tutorial, as well as incorporating the plugin into an existing app. I also tried downgrading cordova-ios & the plugin

**Comment by mixersoft** [comment]
I looked into issue https://github.com/driftyco/ionic-plugin-deploy/issues/73 but the fix was pushed. I updated to the latest version of the plugin, `0.5.6` and still have this problem.

**Comment by gsarfati** [comment]
+1

**Comment by EyalSeagull** [comment]
Hi @Fuiste,

I had the same problem even after installing the 0.5.6 version, but when I removed (thru code) the **my_versions** and **version_count** preferences from NSUserDefaults everything worked fine.

It looked like the **my_versions** preference had an "old" content (only the **UUID** without the **NUMBER|UUID**) and that was the reason it stucked when I run the app.

Can it be the reason for the problem above? Is it possible to check (in the init function) if the format of the NSUserDefaults **my_versions** is an "old" one and clear it if so?

**Comment by mixersoft** [comment]
@EyalSeagull Is that easy to do in xcode? can you share an example?

**Comment by EyalSeagull** [comment]
Hi @mixersoft,

Yes it is wasy to do in XCode. In the **IonicDeploy.m** file I have changed the following function:

```- (void) initialize:(CDVInvokedUrlCommand *)command {
    self.deploy_server = [command.arguments objectAtIndex:1];
}```

To this:

```- (void) initialize:(CDVInvokedUrlCommand *)command {
    self.deploy_server = [command.arguments objectAtIndex:1];
    
    **// TEMPORÁRIO LINES!! Run once and than DELETE this lines**
    **[[NSUserDefaults standardUserDefaults] removeObjectForKey:@"my_versions"];**
    **[[NSUserDefaults standardUserDefaults] removeObjectForKey:@"version_count"];**
}```

Hope this will help.

**Comment by mixersoft** [comment]
@EyalSeagull

I did the following:

file: `IonicDeploy.m`

```
- (void) initialize:(CDVInvokedUrlCommand *)command {
    self.deploy_server = [command.arguments objectAtIndex:1];
    // TEMPORÁRIO LINES!! Run once and than DELETE this lines**
    [[NSUserDefaults standardUserDefaults] removeObjectForKey:@"my_versions"];
    [[NSUserDefaults standardUserDefaults] removeObjectForKey:@"version_count"];
}
```

and I put a breakpoint in that method, but it never ran the code

My xcode console still shows:

```
2016-06-22 21:21:33.148 myapp[37840:490094] uuid is: 
2016-06-22 21:21:33.148 myapp[37840:490094] ignore deploy
2016-06-22 21:21:33.148 myapp[37840:490094] ignore version
```

and I have the following configuration:

```
$ ionic info

Your system information:

Cordova CLI: 5.4.1
Gulp version:  Requiring external module coffee-script/register
Gulp local:   CLI version 3.9.0
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.8.5 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3 Build version 7D175 

$ cordova plugin list
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-app-version 0.1.8 "AppVersion"
cordova-plugin-camera 2.2.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-facebook4 1.7.1 "Facebook Connect"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.0 "SocialSharing"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
ionic-plugin-deploy 0.5.6 "IonicDeploy"
ionic-plugin-keyboard 2.0.1 "Keyboard"
```

any suggestions?

**Comment by EyalSeagull** [comment]
Hi @mixersoft,

I´m getting the same lines as you do in XCode:

```
2016-06-23 01:22:55.171 myApp[39639:5836253] uuid is: 
2016-06-23 01:22:55.171 myApp[39639:5836253] ignore deploy
2016-06-23 01:22:55.171 myApp[39639:5836253] ignore version: 
```

Although my app is running ok (including deploy).

Maybe you can you try putting the lines in the beggining of the **IonicDeploy.m**  `pluginInitialize` function instead?

```
    // TEMPORARY LINES!! Run once and than DELETE this lines
    [[NSUserDefaults standardUserDefaults] removeObjectForKey:@"my_versions"];
    [[NSUserDefaults standardUserDefaults] removeObjectForKey:@"version_count"];
```

Here is a short (uncomment) version of how I use Ionic Deploy process in my app (it will check and download a new version if exists, it will get the Deploy Info and Deploy Metadata and it will even exclude old version to gain space):

```
// Initialize the Deploy Plugin
var deploy = new Ionic.Deploy();

// Guarantee that we are pointing to the "Production" environment
deploy.setChannel("production");

// Check for Deploy Updates
$rootScope.appDeployInfo = {};
$rootScope.appDeployMetadata = {};
doUpdateCheck();

// -------------------------------------------------------------
function doUpdateCheck() {
    deploy.check().then(
        function(hasUpdate) {
            if (hasUpdate) {
                doUpdateDownload();
            } else {
                doUpdateGetInfo();
            }
        },
        function(error) {
            doUpdateGetInfo();
        });
}

// -------------------------------------------------------------
function doUpdateDownload() {
    deploy.download().then(
        function() {
            doUpdateExtract();
        },
        function(error) {
            doUpdateGetInfo();
        },
        function(progress) {
        });
}

// -------------------------------------------------------------
function doUpdateExtract() {
    deploy.extract().then(
        function() {
            deploy.load();
        },
        function(error) {
            doUpdateGetInfo();
        },
        function(progress) {
        });
}

// -------------------------------------------------------------
function doUpdateGetInfo() {
    deploy.info().then(
        function(deployInfo) {
            $rootScope.appDeployInfo = deployInfo;
            doUpdateGetMetadata();
        },
        function(error) {
            doUpdateGetMetadata();
        });
}

// -------------------------------------------------------------
function doUpdateGetMetadata() {
    deploy.getMetadata().then(
        function(metadata) {
            $rootScope.appDeployMetadata = metadata;
            doDeleteOldVersions();
        },
        function(error) {
        });
}

// -------------------------------------------------------------
function doDeleteOldVersions() {
    if (($rootScope.appDeployInfo == undefined) ||
        ($rootScope.appDeployInfo.deploy_uuid == undefined) ||
        ($rootScope.appDeployInfo.deploy_uuid == "") ||
        ($rootScope.appDeployInfo.deploy_uuid == "NO_DEPLOY_AVAILABLE")) {

        return;
    }

    deploy.getVersions().then(
        function(versions) {
            versions.forEach(function(element) {
                if (element != $rootScope.appDeployInfo.deploy_uuid) {
                    deploy.deleteVersion(element).then(
                        function(success) {
                        },
                        function(error) {
                        });
                }
            });
        });
}
```

**Comment by deliverymanager** [comment]
What version of cordova ios platform do you use?
Is it the latest? 4.1.1?

**Comment by EyalSeagull** [comment]
Yes, cordova-ios@4.1.1

`$ sudo ionic info`

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.0
Ionic Framework Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.3.2
Xcode version: Xcode 7.3.1 Build version 7D1014 

`$ sudo cordova plugin list`

com.darktalker.cordova.screenshot 0.1.5 "Screenshot"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-badge 0.7.2 "Badges"
cordova-plugin-camera 2.2.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-crosswalk-webview 1.7.2 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.1 "SocialSharing"
ionic-plugin-deploy 0.5.6 "IonicDeploy"
ionic-plugin-keyboard 2.2.0 "Keyboard"

**Comment by mixersoft** [comment]
**SOLVED!!!**

I updated to `cordova-ios@4.1.1` and it worked. was previously on `3.8.0` or `3.8.1`

use: `ionic platform remove ios; ionic platform add ios`

but make sure you save your `.plist` file and update the  `<key>NSAppTransportSecurity</key>` keys

**Comment by Fuiste** [comment]
Marking this solved, as it hasn't been active for some time and the latest ionic CLI's now install a more recent `cordova-ios`.

Let me know if issues are persisting.
