### ISSUE TITLE
Unable to build IOS with cordova-plugin-zip

### ISSUE THREAD

**Issue by itbeyond** [driftyco/ionic-plugin-deploy#71]
It appears that the ionic-plugin-deploy is not compatible with cordova-plugin-zip when building on IOS. The two libraries cause 68 duplicate symbols linker errors during the build process. It works fine on Android but not IOS.

Building with latest xcode targetting version 9 and latest plugins:
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS:Node Version: v4.4.4

If I remove the ionic-plugin-deploy it compiles perfectly alias deploy does not work.

**Comment by Fuiste** [comment]
This is a known issue, and we're looking into solutions.

I'm closing this because there's a duplicate issue [here](https://github.com/driftyco/ionic-plugin-deploy/issues/13), but this is definitely something we're interested in solving.
