### ISSUE TITLE
plugin break after update the app 

### ISSUE THREAD

**Issue by hossam9995** [driftyco/ionic-plugin-deploy#72]
Hello 

I'am using deploy plugin and  every thing  work fine .

the application catch there is an update and i try to install it ,

,but the problem is after update files throw ionic io plugin all plugins not work no facebook login no google+ no sqllite ,, its like after catch update and download it ,, the plugins not work perfect ,?!

the application work fine but the plugins does not .

my  system info 
 ```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:     Ubuntu 
Node Version: v5.6.0
```

my plugin list 
```
com.cordova.plugins.sms 0.1.8 "Cordova SMS Plugin"
com.ionic.keyboard 1.0.4 "Keyboard"
com.telerik.plugins.nativepagetransitions 0.6.4 "Native Page Transitions"
com.telerik.plugins.wkwebview 0.6.9 "WKWebView Polyfill"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-crosswalk-webview 1.6.1 "Crosswalk WebView Engine"
cordova-plugin-facebook4 1.7.1 "Facebook Connect"
cordova-plugin-geolocation 2.2.0 "Geolocation"
cordova-plugin-google-analytics 0.8.1 "Google Universal Analytics Plugin"
cordova-plugin-googleplus 4.0.8 "Google+"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-splashscreen 4.0.0 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.3-dev "Whitelist"
cordova-plugin-x-socialsharing 5.0.10 "SocialSharing"
cordova-plugin-x-toast 2.4.2 "Toast"
cordova-sqlite-storage 1.4.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 2.3.16 "Diagnostic"
ionic-plugin-deploy 0.5.4 "IonicDeploy"
ionic-plugin-keyboard 1.0.8 "Keyboard"
org.apache.cordova.console 0.2.13 "Console"
org.apache.cordova.device 0.3.0 "Device"
```

also hardware back button does not work 

this photo for the console after install file from ionic io 

![screensdsfsdf](https://cloud.githubusercontent.com/assets/7863464/15588115/151992f8-2395-11e6-821d-68cf110b7f04.png)

**Comment by deliverymanager** [comment]
I would suggest to try creating a new ionic project without any more plugins than the necessary.
Then try adding one by one the plugins to see if anyone of them causes the problem.

**Comment by hossam9995** [comment]
@deliverymanager thanks for reply .. I just would like to know what is  ionic cachebuster mean .. Its like the app after update cant catch cordova.js and cordova_plugin.js files on app directory  .. ..

Thanks

**Comment by Fuiste** [comment]
@hossam9995 first thing, I'd do as @deliverymanager suggested and verify that the problem lies specifically with ionic deploy rather than some other plugin change.

Have you commented out the `cordova.js` in your `index.html`?  This is essential for the Ionic web client to function with deploy.

Finally, the cachebuster you're seeing is just adding ignored query parameters to request URL's so as to avoid device caching of files.   It's nothing you need worry about in this case.

**Comment by hossam9995** [comment]
@Fuiste really thanks you so much ,, it works perfect when you i commented out the cordova.js in my index.html 

thanks again

**Comment by Fuiste** [comment]
Glad to help!
