### ISSUE TITLE
iOS - shouldOverrideLoadWithRequest causing issues with deferred loading

### ISSUE THREAD

**Issue by NickMele** [driftyco/ionic-plugin-deploy#77]
It is very possible I am not doing something correctly, but I believe this method is causing issues with deferred loading. The process I am trying to implement within our app is as follows:

1. User opens app
2. In the background the app checks if there is an update
3. If there is an update, it is downloaded and extracted in the background.
4. next time the user opens the app, the update is applied using `$ionicDeploy.load()`

What seems to be happening though is everything through step 3 works fine. But when the user begins to navigate to another view within the app via `$state.go('')`, according to the debug logs, is triggering the [shouldOverrideLoadWithRequest](https://github.com/driftyco/ionic-plugin-deploy/blob/69e4e82bee678a9fd3e54ae4d26c3d84159838df/src/ios/IonicDeploy.m#L106)

Since the deploy has been extracted when `doRedirect` is called the update gets loaded and redirects the entire app, essentially restarting it and applying the update.

Am I doing something incorrectly, or is this just a bug?

**Comment by Fuiste** [comment]
@NickMele sorry for the delayed response here, but this indeed appears to be a bug at first glance.

I'll look into reproducing it and pushing a fix in the next release of the plugin.

**Comment by shahin8r** [comment]
Experiencing same problem here.

**Comment by Fuiste** [comment]
Hey guys, just a heads up that I've released version `0.6.4` of the deploy plugin, along with my fix for this issue.

Give it a try and let me know if you have any issues!
