### ISSUE TITLE
After app updated with deploy, $ionicPlatform service events do not work!

### ISSUE THREAD

**Issue by deliverymanager** [driftyco/ionic-plugin-deploy#79]
After making an update to the app, $ionicPlatform.on("pause", function(){});
and resume etc events do not work!

**Comment by plnkr2015** [comment]
hi,
i am having an issue which might be related to #79

here is what i am doing-
1. watching for any update
2. if available download
3. show a message to user
4. upon user confirmation, calling deploy.load()
5. deploy is successful and app restarts

up to step 5, it works good but when app restarts i don't see any plugin loaded. also the buttons and etc when i click them nothing happens. basically app is not responsive when app restarts. any new deploy is not identified by the app at this point.

after that if i completely kill the app and open it, i can see the changes are deployed correctly and everything works fine. the app now finds the new deploy correctly.

i am testing this on ios
cordova platform version
Installed platforms:
  ios 4.1.0

ionic info

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.5
Xcode version: Xcode 7.3.1 Build version 7D1014 

please help.

regards,
arun

**Comment by pawurb** [comment]
I am facing an issue that might be connected. I manuall download, extract and apply (`deploy.load()`) update using the codes from here http://docs.ionic.io/docs/deploy-updating-apps. I can see that Objective-C code is properly called and `"Reloading the UIWebView."` message is displayed. However after the view reload looks like the changes are not applied. I can still see the previous version. Only force quitting the app and starting it again makes the new version appear. I am using 0.6.1 version of the plugin. My `ionic info` output:

```
Cordova CLI: 6.3.0
Gulp version:  Requiring external module coffee-script/register
Gulp local:   CLI version 3.9.0
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.8.2
ios-sim version: 5.0.3
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.3 Build version 7D175
```
any clues about what's wrong appreciated.

**Comment by Fuiste** [comment]
@pawurb perfect timing.  Try deploy version `0.6.2`, which I just released to solve this issue.  

I believe this issue is solved now, but let me know if the problem persists and I can re-open it.
