### ISSUE TITLE
White Screen of Death

### ISSUE THREAD

**Issue by andrewoodleyjr** [driftyco/ionic-plugin-deploy#83]
Greetings,

Im using Ionic Deploy to update an app. Initially everything checks out fine after a successful update... However after restarting the iOS app after a deploy a blank white screen shows.

Debug Errors - (Safari)
1. cordova.js is already included...'
```
Error: cordova already defined
```
2. app module is not Failed to instantiate module app due to: 
```
Error: [$injector:modulerr] Failed to instantiate module ib-mobile due to:
[$injector:nomod] Module 'ib-mobile' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

**Comment by Fuiste** [comment]
Hey @andrewoodleyjr, couple quick questions before I can look into this.

* Are you running ionic 1 or 2?
* Are you using the `ionic-platform-web-client` or the `cloud-angular` service?
* Which version of the deploy plugin are you running?

**Comment by andrewoodleyjr** [comment]
Hey @Fuiste, Thanks for the prompt response.
1. Ionic 1, 
2. `ionic-platform-web-client`
3. `ionic deploy version 0.6.0`

**Comment by Fuiste** [comment]
Good to know.  I'm wondering if this issue is tied to my ionic 2 support changes in 0.6.0

Can you confirm whether the issue is still occurring if you use 0.5.7?

**Comment by andrewoodleyjr** [comment]
Implementing now.

**Comment by andrewoodleyjr** [comment]
@Fuiste Tried a couple times using 0.5.7 unfortunately same issue. 
Trying 0.5.0 now

**Comment by andrewoodleyjr** [comment]
@Fuiste v0.5.7 and v0.5.0 - No Dice

**Comment by andrewoodleyjr** [comment]
@Fuiste I believe the problem was related to another issue found here. https://github.com/driftyco/ng-cordova/issues/172

**Comment by Fuiste** [comment]
Glad you got it figured out @andrewoodleyjr, was just about to post a response here that I was having trouble reproducing the issue.
