### ISSUE TITLE
Deploy.load() Not Reloading App Immediately

### ISSUE THREAD

**Issue by Fuiste** [driftyco/ionic-plugin-deploy#86]
_From @amymarsh4work on August 23, 2016 19:27_

Hi,
I'm working on getting the Deploy functionality working in my Ionic 2 -ts app. It's mostly there, but having a problem - the deploy.done() doesn't seem to be working for me. I'm not seeing the updated app until I manually close the app and reopen it.

I can reproduce this by deploying a new build to the production channel, then running 'ionic run ios -lc' with my device connected.

Any help would be appreciated. :)

**Here's my 'ionic info':**
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175 

**Here's the relevant snippet from my app.ts:**
platform.ready().then(() => {
            // Check for updates then download and apply.
            this.deploy.check().then((hasUpdate) => {
                if (hasUpdate) {
                    deploy.download().then(() => {
                        deploy.extract().then(() => {
                            deploy.load();
                        }, (extractError) => {
                            console.log('Error extracting update: ' + extractError);
                        });
                    }, (updateError) => {
                        console.log('Error downloading update: ' + updateError);
                    });
                }
            }).then(() => {
                deploy.getMetadata().then((metadata) => {
                    console.log(metadata.release);
                }, (getMetadataErr) => {
                    console.log('getMetadataErr: ' + getMetadataErr);
                });
            }, (err) => {
                console.log('Error checking for updates: ' + err);
            });
        });
 
Thanks,
Amy

_Copied from original issue: driftyco/ionic-cloud-angular#11_

**Comment by Fuiste** [comment]
_From @Manduro on August 23, 2016 19:42_

I can conform this issue.

**Comment by Fuiste** [comment]
_From @dwieeb on August 23, 2016 19:44_

Using the new version of `ionic-plugin-deploy`, I presume? `0.6.0` or `0.6.1`?

**Comment by Fuiste** [comment]
_From @Manduro on August 23, 2016 19:51_

Using 0.6.0, happenings consistentst and I don't think the 0.6.1 fix is related.

It also loaded the originally packaged app on one occasion, after having updated some time before. A restart loaded the update back in. I can't reproduce that though.

**Comment by Fuiste** [comment]
_From @dwieeb on August 23, 2016 19:52_

@Fuiste, thoughts? Is the plugin's `load()` function broken?

**Comment by Fuiste** [comment]
_From @amymarsh4work on August 23, 2016 19:53_

Correct - I'm using 0.6.0.

**Comment by Fuiste** [comment]
@dwieeb I'll look into it, everything seems kosher on my testing app, but I'll try a fresh one as soon as I'm able.

**Comment by Fuiste** [comment]
@dwieeb and @amymarsh4work I've identified the problem, it was stemming from reloading the webview on redirect, specifically in iOS.

I'm cutting a new release now, going to move this issue to the deploy plugin and comment there when it's fixed.

**Comment by Fuiste** [comment]
💥💥💥

And there we go.  Version `0.6.2` of the deploy plugin has just been released.

Let me know if you have any issues, but it appears good to go on both of my devices.

Thanks for catching this one!

**Comment by kleeb** [comment]
looks like its not fixed

**Comment by Fuiste** [comment]
@kleeb can you provide a reproduction case?  It appears to be working as expected on my end.

**Comment by numerized** [comment]
This issue appears with wkwebview from ionic team.

**Comment by ericb** [comment]
related #99

**Comment by tobiasmuecksch** [comment]
@kleeb Please reopen the issue. It definitely is not fixed!
