### ISSUE TITLE
Possible to get list of latest deploys?

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic-plugin-deploy#87]
Hi there!

I am trying to get a list of the most recent deploys for a given channel in ionic.io, and as far as I can tell, it isn't possible with this plugin.  My goal is to be able to determine if there is a new binary update (meaning that the currently installed version is lower than the newest deployed "minVersion" in ionic.io).  Is that possible?

Thanks for your time!

**Comment by ericb** [comment]
This is not currently possible, but it is something you could do with our deploy API if you have access to your own backend. This is definitely something we want to support with a future plugin update though, so you can notify users that a binary update is available.
