### ISSUE TITLE
[Android][bug] deploy.load causes issues by recreating plugins on restart

### ISSUE THREAD

**Issue by keithdmoore** [driftyco/ionic-plugin-deploy#91]
As an example, when deploy.load restarts my app I am unable to get a connection from the sqlite connection pool.  App goes into an infinite loop due to this.

Tested on multiple Android devices.  For example, Samsung S5 with Android 6.0.1

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.5 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v5.8.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by Fuiste** [comment]
Fixed in PR #91, thanks for the submission!
