### ISSUE TITLE
App update via deploy not persisting

### ISSUE THREAD

**Issue by thoems** [driftyco/ionic-plugin-deploy#94]
On iOS (Android is working smoothly) when updating the app via the deploy service at first the app is correctly updated, but after restarting the app for two or three times it reverts to the initially installed version from the AppStore.

This seems to be a regression, an issue already dealt with and fixed in earlier releases:
https://github.com/driftyco/ionic-plugin-deploy/issues/60

iOS Version: 9.x and 10.x
Cordova CLI: 6.3.0
Gulp version:  CLI version 1.2.2
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS: Linux  4.7.5-1-ARCH
Node Version: v6.7.0

cordova-plugin-device 1.1.3 "Device"
cordova-plugin-inappbrowser 1.5.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
**ionic-plugin-deploy 0.6.4 "IonicDeploy"**
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.8.2 "PushPlugin"

**cordova-ios: 4.2.1**

Any help would be appreciated, thanks!

**Comment by thoems** [comment]
Tried version ionic-plugin-deploy 0.5.7 - no luck either.

**Comment by Fuiste** [comment]
I've just published version `0.6.5` of the plugin to address this issue.  Let me know if you have any trouble.

**Comment by thoems** [comment]
I can verify that it works perfectly now. Thank you and a thumbs up for the ionic deploy feature in general.
