### ISSUE TITLE
Reloading the update using deploy.load() does not work on iOS.

### ISSUE THREAD

**Issue by kleeb** [driftyco/ionic-plugin-deploy#98]
Testing deploy on Ionic2 RC0 with https://github.com/driftyco/cordova-plugin-wkwebview-engine.git plugin.

App does not get reloaded after update. After restart new version is there.

Looks like the problem was closed here, but still appears: https://github.com/driftyco/ionic-plugin-deploy/issues/86

Tested on simple cutePuppyPics startup template with this code:

```
platform.ready().then(() => {
      this.deploy.check().then((hasUpdate) => {
        if (hasUpdate) {
          deploy.download().then(() => {
            deploy.extract().then(() => {
              deploy.load();
            });
          });
        }
      });
    });
```

Tried on iPhone5 (iOS9) and iPhone6 (iOS10). The same behaviour for both.
On simulator everything works like it should, so I guess its something related to wkwebview.

**Comment by numerized** [comment]
https://github.com/driftyco/ionic-plugin-deploy/issues/96

**Comment by numerized** [comment]
Hi guys

Facing the same problem, any news ?

**Comment by numerized** [comment]
This issue appears with wkwebview from ionic team.

**Comment by ericb** [comment]
Hey all,

Just wanted to drop in and say that using wkwebview will not be supported for Deploy until wkwebview see's an official release. We will definitely be making any changes necessary when that happens.

I will open up an issue to track the support for this and link it here.

**Comment by ericb** [comment]
Check out issue #99 to see more information.
